In [2]:
import numpy as np



In [3]:
# 1. Create a 1D array of integers from 0 to 9.
x = np.random.rand(10,1)
print(x)

[[0.49592371]
 [0.70610011]
 [0.7297064 ]
 [0.25490937]
 [0.77098431]
 [0.42020297]
 [0.73819897]
 [0.6577272 ]
 [0.08082517]
 [0.50507483]]


In [4]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8.
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:


# 3. Create a 3x3 identity matrix.
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:


# 4. Generate a 2x3 array with random numbers between 0 and 1.
x = np.random.rand(2,3)
print(x)

[[0.95707533 0.84288108 0.3868536 ]
 [0.51807338 0.41888406 0.37292123]]


In [7]:


# 5. Create a 5x5 array with all values as 2.
print(np.ones([5,5])*2)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [8]:


# 6. Create a 3x3x3 array with random values.
x = np.random.rand(3,3,3)
print(x)

[[[0.5137771  0.23705342 0.11054311]
  [0.00368371 0.86168775 0.91680237]
  [0.97506274 0.91300231 0.68636004]]

 [[0.66151642 0.83385573 0.90259811]
  [0.0673478  0.59839605 0.90536887]
  [0.68289124 0.96249244 0.5731658 ]]

 [[0.81266764 0.42475993 0.91376236]
  [0.42636405 0.04277489 0.56678373]
  [0.42979074 0.74022911 0.04866032]]]


In [9]:


# 7. Create a 10x10 array with random values and find the minimum and maximum values.
x = np.random.rand(10,10)
print(x)
print(x.min(),x.max())

[[0.71906011 0.63690673 0.83851992 0.32587849 0.47018829 0.34600191
  0.77342561 0.09783758 0.82546695 0.13229342]
 [0.81278681 0.78891765 0.71478143 0.23827531 0.44734648 0.5186733
  0.74268319 0.75365786 0.0591259  0.24289082]
 [0.90526639 0.56615584 0.36948738 0.73067985 0.48587976 0.94862567
  0.00444615 0.35586109 0.39150138 0.96016867]
 [0.42471805 0.15515987 0.48161507 0.2117127  0.44397768 0.68798772
  0.29367743 0.57401822 0.3106799  0.52854452]
 [0.88665482 0.21855618 0.63225161 0.68778476 0.09316835 0.44100645
  0.75411322 0.58193114 0.9409728  0.59016383]
 [0.72903151 0.52247262 0.64523692 0.0782557  0.77562927 0.53565468
  0.8411459  0.54946271 0.65195408 0.16180275]
 [0.49427947 0.74344792 0.87925354 0.9827828  0.34962223 0.7403402
  0.72515643 0.29020911 0.64937891 0.98474665]
 [0.79877031 0.84564158 0.59245899 0.18240918 0.77979801 0.16496276
  0.16061071 0.59365165 0.97291529 0.72529578]
 [0.07962826 0.68194289 0.63746242 0.71361937 0.73839895 0.63812336
  0.09115879 0

In [10]:


# 8. Create a random vector of size 30 and find the mean value.
x = np.random.rand(30)
print(x,'\n',x.mean())

[0.05409791 0.04296828 0.5306402  0.21178274 0.01193526 0.06756176
 0.95911639 0.51436658 0.88510999 0.23272049 0.90680071 0.44839463
 0.15207757 0.32936439 0.80104136 0.92267538 0.23884661 0.43693998
 0.57945652 0.81872492 0.85525074 0.05877707 0.22158529 0.97236902
 0.26339241 0.96241932 0.22991289 0.03443388 0.69998051 0.22436722] 
 0.4555703339979703


In [11]:
x = np.random.rand(30)
a = np.random.rand(1,30)
b = np.random.rand(1,1,30)
c = np.random.rand(1,30,1)
d = np.random.rand(30,1,1)
print(x,a,b,c,d)

[0.9581728  0.19040223 0.85611527 0.53573224 0.80401449 0.05070066
 0.45745336 0.48386314 0.99347588 0.9166211  0.12191887 0.80068877
 0.36985372 0.34954024 0.59013525 0.70151303 0.34964627 0.61770401
 0.56791645 0.19980348 0.28094371 0.55644619 0.64008076 0.06392554
 0.94555618 0.06356402 0.30120959 0.00207556 0.78995177 0.73864368] [[0.569781   0.21252037 0.75062866 0.17441515 0.94548813 0.72012269
  0.68244108 0.94352325 0.33378533 0.24020289 0.6124253  0.30670284
  0.05303502 0.56999868 0.6892021  0.73761334 0.75993484 0.92249273
  0.1331896  0.98886496 0.51166841 0.51062726 0.80926898 0.69718069
  0.60253204 0.78226827 0.70621713 0.51966198 0.7624688  0.52854069]] [[[0.80422212 0.89349482 0.16956939 0.20900791 0.2587812  0.09257167
   0.43218265 0.87740871 0.77673337 0.5750688  0.4286287  0.85343619
   0.28632111 0.44531933 0.35709342 0.26845272 0.74343158 0.61916292
   0.18066898 0.66065302 0.56254703 0.01700991 0.73221891 0.99571505
   0.94433253 0.37005645 0.77150183 0.33239663

In [12]:


# 10. Create a 8x8 matrix and fill it with a checkerboard pattern (0s and 1s).
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [13]:


# 9. Create a 2d array with 1 on the border and 0 inside.
x = np.zeros([5,5])
print(x)
x[0,:] = 1
x[-1,:] = 1
x[:,0] = 1
x[:,-1] = 1
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
# 11. Create a random vector of size 10 and sort it.
x = np.random.rand(10)
x = sorted(x)
print(x)

[0.012639919296574598, 0.1439993604070473, 0.16330445155792117, 0.28481044069729855, 0.4972978644636835, 0.5035748514583366, 0.5444469672303518, 0.5487905349465884, 0.5557040096467906, 0.8046243681840202]


In [15]:


# 12. How to reverse a numpy array?
x = np.array([1,2,3,4,5])
print(x[::-1])

[5 4 3 2 1]


In [16]:


# 13. How to stack two arrays vertically?
x = np.random.rand(2,2)
y = np.random.rand(2,2)
xy = np.vstack((x,y))
print(xy)

[[6.89337839e-01 5.51346972e-04]
 [3.98572526e-01 5.96725510e-01]
 [5.35715079e-01 5.47712608e-01]
 [2.18517025e-01 9.28694928e-01]]


In [17]:


# 15. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:


# 14. How to stack two arrays horizontally?
x = np.random.rand(2,2)
y = np.random.rand(2,2)
xy = np.hstack((x,y))
print(xy)

[[0.47448794 0.47792341 0.99952679 0.23642948]
 [0.11791771 0.55586127 0.65546728 0.75084335]]


In [19]:
# 16. Create a 5x5 matrix with values 1,2,3,4 just above the diagonal.
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix[:,1:], [1, 2, 3, 4])
print(matrix)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [20]:


# 18. Create a checkerboard 8x8 matrix using the tile function.
x = np.array([[1,0],[0,1]])
x = np.tile(x,(4,4))
print(x)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [21]:

# 19. Normalize a 5x5 random matrix.
random_matrix = np.random.rand(5,5)
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)

[[0.4472544  0.30676703 0.8689563  0.58880295 0.28729721]
 [0.54262264 0.42668724 0.15245641 0.25382339 0.078493  ]
 [0.43115776 0.42055569 0.09018531 0.23351529 0.10731824]
 [0.35870898 0.         1.         0.15703129 0.17655368]
 [0.51921924 0.40442815 0.71105398 0.01137792 0.79854926]]


In [22]:


# 20. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product).
x = np.random.rand(5,3)
y = np.random.rand(3,5)
result = np.dot(x, y)
print(result)

[[0.52256893 1.69325321 1.99002067 0.84036169 1.21200349]
 [0.51168061 1.59587546 1.67811974 0.71539713 1.13943329]
 [0.36040633 1.10760095 0.9978813  0.51913083 0.72989942]
 [0.60121538 1.95190267 2.2345457  1.00128952 1.35902514]
 [0.40008737 1.19571927 0.92949479 0.52977881 0.76794361]]


In [23]:
# 21. Extract the integer part of a random array.
import numpy as np

# Generate a random array with both integers and floating-point numbers
random_array = np.random.rand(5) * 10  # Generate 5 random numbers between 0 and 10

# Extract the integer part of each element
integer_part_array = random_array.astype(int)

print("Random Array:", random_array)
print("Integer Part Array:", integer_part_array)


Random Array: [4.6452041  9.29722758 0.80683011 9.28554166 0.53017483]
Integer Part Array: [4 9 0 9 0]


In [25]:

# 22. Create a 5x5 matrix with row values ranging from 0 to 4.
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.arange(5).reshape(1, -1) + np.arange(5).reshape(-1, 1)
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


In [32]:

# 23. Create a random vector of size 10 and replace the maximum value by 0.
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print(random_vector)

print("Random Vector with Maximum Value Replaced:", random_vector)


[0.17350883 0.4209691  0.71991269 0.18816544 0.54255189 0.
 0.48911963 0.77827668 0.57240704 0.12277196]
Random Vector with Maximum Value Replaced: [0.17350883 0.4209691  0.71991269 0.18816544 0.54255189 0.
 0.48911963 0.77827668 0.57240704 0.12277196]


In [33]:

# 24. How to find the closest value (to a given scalar) in an array?
import numpy as np

def find_closest_value(array, scalar):
    index = np.abs(array - scalar).argmin()  # Find the index with the minimum absolute difference
    closest_value = array[index]
    return closest_value

# Example usage:
array = np.array([1, 3, 5, 7, 9])
scalar = 6
closest_value = find_closest_value(array, scalar)
print("Closest value to", scalar, "in the array:", closest_value)


Closest value to 6 in the array: 5


In [36]:

# 25. Subtract the mean of each row of a matrix.
import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
mean_subtracted_matrix = matrix - np.mean(matrix, axis=1, keepdims=True)


print("Original Matrix:")
print(matrix)
print("\nMean Subtracted Matrix:")
print(mean_subtracted_matrix)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean Subtracted Matrix:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [37]:
# 26. How to sort an array by the nth column?
import numpy as np

# Create a sample array
array = np.array([[1, 4, 3],
                  [6, 2, 8],
                  [5, 7, 9]])

# Define the index of the column by which to sort
n = 1  # Sort by the second column (0-indexed)

# Get the indices that would sort the array by the nth column
sorted_indices = np.argsort(array[:, n])

# Sort the array by the nth column using the sorted indices
sorted_array = array[sorted_indices]

print("Original Array:")
print(array)
print("\nSorted Array by the", n+1, "column:")
print(sorted_array)


Original Array:
[[1 4 3]
 [6 2 8]
 [5 7 9]]

Sorted Array by the 2 column:
[[6 2 8]
 [1 4 3]
 [5 7 9]]


In [39]:

# 27. How to tell if a given 2D array has null columns?
import numpy as np

def has_null_columns(array):
    column_sums = np.sum(array, axis=0)  # Calculate the sum of each column
    return np.any(column_sums == 0)  # Check if any column sum is zero

# Example usage:
array_with_null_columns = np.array([[0, 1, 2],
                                    [0, 0, 0],
                                    [3, 4, 5]])

array_without_null_columns = np.array([[1, 2, 3],
                                       [4, 5, 6],
                                       [7, 8, 9]])

print("Array with null columns:", has_null_columns(array_with_null_columns))
print("Array without null columns:", has_null_columns(array_without_null_columns))


Array with null columns: False
Array without null columns: False


In [41]:

# 28. Create an array of 3x3x3 with random values and find the sum over the last two axes.
import numpy as np

# Create a 3x3x3 array with random values
array = np.random.rand(3, 3, 3)

# Find the sum over the last two axes
sum_over_last_two_axes = np.sum(array, axis=(-2, -1))

print("Original Array:")
print(array)
print("\nSum over the last two axes:")
print(sum_over_last_two_axes)


Original Array:
[[[0.77639388 0.76627425 0.28048299]
  [0.15564779 0.62773066 0.00443543]
  [0.41956242 0.19910246 0.97045694]]

 [[0.15977671 0.09341364 0.19027253]
  [0.1959879  0.91270757 0.57855323]
  [0.46794218 0.6841639  0.88852292]]

 [[0.28359128 0.93859816 0.29994189]
  [0.69147939 0.06232336 0.00205404]
  [0.57607171 0.16959592 0.28839806]]]

Sum over the last two axes:
[4.20008683 4.17134059 3.31205381]


In [44]:

# 29. How to swap two rows of an array?
import numpy as np

def swap_rows(array, row1, row2):
    array[[row1, row2]] = array[[row2, row1]]

# Example usage:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print("Original Array:")
print(array)

# Swap rows 0 and 1
swap_rows(array, 0, 1)

print("\nArray after swapping rows 0 and 1:")
print(array)

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping rows 0 and 1:
[[4 5 6]
 [1 2 3]
 [7 8 9]]


In [42]:

# 30. How to get the diagonal of a dot product?
import numpy as np

# Create two sample matrices
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Perform the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Get the diagonal of the dot product
diagonal = np.diagonal(dot_product)

print("Dot Product:")
print(dot_product)
print("\nDiagonal of the Dot Product:")
print(diagonal)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal of the Dot Product:
[30 69 90]


In [47]:
# 31. How to find the most frequent value in an array?
import numpy as np

def most_frequent_value(array):
    counts = np.bincount(array)  # Count occurrences of each value
    most_frequent_index = np.argmax(counts)  # Find the index of the maximum count
    most_frequent_value = most_frequent_index  # The most frequent value is the index itself
    return most_frequent_value

# Example usage:
array = np.array([1, 2, 3, 1, 2, 2, 3, 2, 2, 1])
most_frequent = most_frequent_value(array)
print("Most frequent value in the array:", most_frequent)



Most frequent value in the array: 2


In [48]:

# 32. How to get the n largest values of an array?
import numpy as np

def n_largest_values(array, n):
    sorted_indices = np.argsort(array)  # Get the indices that would sort the array
    largest_indices = sorted_indices[-n:]  # Get the indices of the n largest values
    largest_values = array[largest_indices]  # Get the n largest values
    return largest_values

# Example usage:
array = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
n = 3
largest_values = n_largest_values(array, n)
print("The", n, "largest values in the array:", largest_values)



The 3 largest values in the array: [5 6 9]


In [49]:

# 33. How to create a record array from a regular array?
import numpy as np

# Define a regular array
regular_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Define field names for each column
field_names = ['column1', 'column2', 'column3']

# Create a record array from the regular array
record_array = np.core.records.fromarrays(regular_array.T, names=field_names)

print("Regular Array:")
print(regular_array)
print("\nRecord Array:")
print(record_array)



Regular Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Record Array:
[(1, 2, 3) (4, 5, 6) (7, 8, 9)]


In [50]:


# 34. Consider a large vector Z, compute Z to the power of 3 using three different methods.
import numpy as np

# Define a large vector Z (for example)
Z = np.random.rand(1000000)  # 1 million random numbers

# Method 1: Using a loop
def cube_using_loop(Z):
    result = np.empty_like(Z)
    for i, z in enumerate(Z):
        result[i] = z ** 3
    return result

# Method 2: Using numpy's element-wise power function
def cube_using_np_power(Z):
    return np.power(Z, 3)

# Method 3: Using the ** operator
def cube_using_operator(Z):
    return Z ** 3

# Test and compare the results
result_loop = cube_using_loop(Z)
result_np_power = cube_using_np_power(Z)
result_operator = cube_using_operator(Z)

# Check if all methods produce the same result
print("Are the results from all methods identical?")
print(np.allclose(result_loop, result_np_power) and np.allclose(result_loop, result_operator))


Are the results from all methods identical?
True


In [51]:

# 35. Consider two arrays A and B, check if they are equal.
import numpy as np

# Example arrays A and B
A = np.array([1, 2, 3])
B = np.array([1, 2, 3])

# Check if arrays A and B are equal
are_equal = np.array_equal(A, B)

print("Are arrays A and B equal?", are_equal)


Are arrays A and B equal? True


In [52]:

# 36. Create random vector of size 10 and replace the maximum value by 0.
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector with Maximum Value Replaced:", random_vector)


Random Vector with Maximum Value Replaced: [0.25690046 0.44844054 0.0997247  0.0397505  0.06316166 0.27134941
 0.05374979 0.29893242 0.36276084 0.        ]


In [53]:

# 37. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area.
import numpy as np

# Define the number of points in each dimension
n_points = 5

# Generate 'x' and 'y' coordinates covering the [0,1]x[0,1] area
x_coordinates = np.linspace(0, 1, n_points)
y_coordinates = np.linspace(0, 1, n_points)

# Create a meshgrid of 'x' and 'y' coordinates
X, Y = np.meshgrid(x_coordinates, y_coordinates)

# Create a structured array with 'x' and 'y' coordinates
structured_array = np.column_stack((X.ravel(), Y.ravel()))

print("Structured Array with 'x' and 'y' coordinates:")
print(structured_array)


Structured Array with 'x' and 'y' coordinates:
[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.25]
 [0.25 0.25]
 [0.5  0.25]
 [0.75 0.25]
 [1.   0.25]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   0.75]
 [0.25 0.75]
 [0.5  0.75]
 [0.75 0.75]
 [1.   0.75]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


In [56]:
import numpy as np

# Print minimum and maximum representable values for integer types
print("Integer types:")
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

# Print minimum and maximum representable values for unsigned integer types
print("\nUnsigned integer types:")
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")

# Print minimum and maximum representable values for floating-point types
print("\nFloating-point types:")
for dtype in [np.float16, np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: Min = {info.min}, Max = {info.max}")


Integer types:
int8: Min = -128, Max = 127
int16: Min = -32768, Max = 32767
int32: Min = -2147483648, Max = 2147483647
int64: Min = -9223372036854775808, Max = 9223372036854775807

Unsigned integer types:
uint8: Min = 0, Max = 255
uint16: Min = 0, Max = 65535
uint32: Min = 0, Max = 4294967295
uint64: Min = 0, Max = 18446744073709551615

Floating-point types:
float16: Min = -65504.0, Max = 65504.0
float32: Min = -3.4028234663852886e+38, Max = 3.4028234663852886e+38
float64: Min = -1.7976931348623157e+308, Max = 1.7976931348623157e+308


In [57]:

# 39. How to negate a boolean, or to change the sign of a float inplace?
# Original boolean value
boolean_value = True

# Negate the boolean value
negated_boolean = not boolean_value

print("Original boolean value:", boolean_value)
print("Negated boolean value:", negated_boolean)

# Original float value
float_value = 3.14

# Change the sign of the float value in place
float_value *= -1

print("Original float value:", float_value)


Original boolean value: True
Negated boolean value: False
Original float value: -3.14


In [58]:

# 43. How to round away from zero a float array?
import numpy as np

# Example float array
float_array = np.array([-2.7, -1.5, 0.0, 1.5, 2.7])

# Round away from zero
rounded_array = np.where(float_array >= 0, np.ceil(float_array), np.floor(float_array))

print("Original float array:", float_array)
print("Rounded away from zero:", rounded_array)


Original float array: [-2.7 -1.5  0.   1.5  2.7]
Rounded away from zero: [-3. -2.  0.  2.  3.]


In [59]:

# 44. How to find common values between two arrays?
import numpy as np

# Example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between array1 and array2
common_values = np.intersect1d(array1, array2)

print("Common values between array1 and array2:", common_values)


Common values between array1 and array2: [3 4 5]


In [60]:

# 45. How to ignore all numpy warnings (not recommended)?
import numpy as np

# Ignore all NumPy warnings temporarily
np.seterr(all='ignore')

# Your code here...

# Reset NumPy warning settings to default
np.seterr(all='warn')


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [61]:

# 47. How to get the dates of yesterday, today and tomorrow?
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Get yesterday's date
yesterday = today - timedelta(days=1)

# Get tomorrow's date
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-03-21
Today: 2024-03-22
Tomorrow: 2024-03-23


In [62]:

# 48. How to get all the dates corresponding to the month of July 2016?
from datetime import datetime, timedelta

# Define the start date and end date for July 2016
start_date = datetime(2016, 7, 1)
end_date = datetime(2016, 8, 1)

# Generate all the dates for the month of July 2016
dates_of_july_2016 = [start_date + timedelta(days=i) for i in range((end_date - start_date).days)]

print("Dates corresponding to the month of July 2016:")
for date in dates_of_july_2016:
    print(date)


Dates corresponding to the month of July 2016:
2016-07-01 00:00:00
2016-07-02 00:00:00
2016-07-03 00:00:00
2016-07-04 00:00:00
2016-07-05 00:00:00
2016-07-06 00:00:00
2016-07-07 00:00:00
2016-07-08 00:00:00
2016-07-09 00:00:00
2016-07-10 00:00:00
2016-07-11 00:00:00
2016-07-12 00:00:00
2016-07-13 00:00:00
2016-07-14 00:00:00
2016-07-15 00:00:00
2016-07-16 00:00:00
2016-07-17 00:00:00
2016-07-18 00:00:00
2016-07-19 00:00:00
2016-07-20 00:00:00
2016-07-21 00:00:00
2016-07-22 00:00:00
2016-07-23 00:00:00
2016-07-24 00:00:00
2016-07-25 00:00:00
2016-07-26 00:00:00
2016-07-27 00:00:00
2016-07-28 00:00:00
2016-07-29 00:00:00
2016-07-30 00:00:00
2016-07-31 00:00:00


In [64]:

# 49. How to compute ((A+B)*(-A/2)) in place (without copy)?
import numpy as np

import numpy as np

# Example arrays A and B (convert to float type)
A = np.array([1, 2, 3], dtype=float)
B = np.array([4, 5, 6], dtype=float)

# Compute the expression in place
result = np.empty_like(A)

np.multiply(A, -0.5, out=result)  # Compute -A/2 in place and store in result
np.add(A, B, out=A)                # Compute A+B in place and store in A
np.multiply(A, result, out=A)      # Compute (A+B)*(-A/2) in place and store in A

print("Result:", A)


Result: [ -2.5  -7.  -13.5]


In [65]:

# 50. Create a numpy array sequence from 0 to 10 with a step of 0.5.
import numpy as np

# Create a numpy array sequence from 0 to 10 with a step of 0.5
array_sequence = np.arange(0, 10.5, 0.5)

print("Array sequence from 0 to 10 with a step of 0.5:")
print(array_sequence)


Array sequence from 0 to 10 with a step of 0.5:
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]
